# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_study'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hobbis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('year', models.PositiveIntegerField()),
            ],
        ),
    ]
