# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 14:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_hobbis'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hobbis',
            new_name='Hobby',
        ),
    ]
