# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 12:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20170831_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Название')),
                ('phone_number', models.CharField(max_length=14, verbose_name='Номер телефона')),
                ('region', models.CharField(blank=True, max_length=32, verbose_name='Регион')),
                ('site', models.URLField(blank=True, db_index=True, verbose_name='Сайт')),
            ],
        ),
        migrations.RemoveField(
            model_name='work',
            name='name',
        ),
        migrations.AlterField(
            model_name='work',
            name='desc',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='work',
            name='post',
            field=models.CharField(max_length=32, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='work',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Organization', verbose_name='Организация'),
        ),
    ]
