# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20170904_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='period',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
