# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_work_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='site',
            field=models.URLField(blank=True, db_index=True, verbose_name='Сайт'),
        ),
    ]
